### ISSUE TITLE
Received "exception does not have a valid/acceptable signature to derive an expiration date from." when using public key from pgp command line

### ISSUE THREAD

**Issue by svemula09** [pgpainless/sop-java#25]
org.pgpainless.exception.KeyException$UnacceptableSelfSignatureException: Key 2C930A1D0D48D79B2EC26E677F9614509F5EEB37 does not have a valid/acceptable signature to derive an expiration date from.
        at org.pgpainless.encryption_signing.EncryptionOptions.addAsRecipient(EncryptionOptions.java:298)
        at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:265)
        at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:253)
        at org.pgpainless.encryption_signing.EncryptionOptions.addRecipients(EncryptionOptions.java:181)
        at org.pgpainless.sop.EncryptImpl.withCert(EncryptImpl.java:109)
        at sop.operation.Encrypt.withCert(Encrypt.java:147)

**Comment by vanitasvitae** [comment]
What version of sop-java / pgpainless are you using?
